In [1]:
##!pip install snscrape

Collecting snscrape
  Downloading snscrape-0.4.3.20220106-py3-none-any.whl (59 kB)
Requirement already satisfied: lxml in c:\programdata\anaconda3\lib\site-packages (from snscrape) (4.6.3)
Requirement already satisfied: requests[socks] in c:\programdata\anaconda3\lib\site-packages (from snscrape) (2.26.0)
Requirement already satisfied: beautifulsoup4 in c:\programdata\anaconda3\lib\site-packages (from snscrape) (4.10.0)
Requirement already satisfied: filelock in c:\programdata\anaconda3\lib\site-packages (from snscrape) (3.3.1)
Requirement already satisfied: soupsieve>1.2 in c:\programdata\anaconda3\lib\site-packages (from beautifulsoup4->snscrape) (2.2.1)
Requirement already satisfied: idna<4,>=2.5 in c:\programdata\anaconda3\lib\site-packages (from requests[socks]->snscrape) (3.2)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\programdata\anaconda3\lib\site-packages (from requests[socks]->snscrape) (2.0.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\programdata\anaconda3\lib\site-packages (from requests[socks]->snscrape) (2021.10.8)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\professor\appdata\roaming\python\python39\site-packages (from requests[socks]->snscrape) (1.25.11)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in c:\programdata\anaconda3\lib\site-packages (from requests[socks]->snscrape) (1.7.1)
Installing collected packages: snscrape
Successfully installed snscrape-0.4.3.20220106

WARNING: Ignoring invalid distribution -rllib3 (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rllib3 (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rllib3 (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rllib3 (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rllib3 (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rllib3 (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rllib3 (c:\programdata\anaconda3\lib\site-packages)

In [2]:
import pandas as pd
import snscrape.modules.twitter as sntwitter

In [3]:
query = "(#30DaysOfLearning OR #NG30DaysOfLearning) until:2022-07-21 since:2022-05-01"
tweets = []
limit = 30000


for tweet in sntwitter.TwitterHashtagScraper(query).get_items():
    
    if len(tweets) == limit:
        break
    else:
        tweets.append([tweet.date, tweet.url, tweet.user.username, tweet.sourceLabel, tweet.user.location, tweet.content, tweet.likeCount, tweet.retweetCount,  tweet.quoteCount, tweet.replyCount])
        
df = pd.DataFrame(tweets, columns=['Date', 'TweetURL','User', 'Source', 'Location', 'Tweet', 'Likes_Count','Retweet_Count', 'Quote_Count', 'Reply_Count'])

df.to_csv('30DLTweets.csv')

In [4]:
df.head()

,Date,TweetURL,User,Source,Location,Tweet,Likes_Count,Retweet_Count,Quote_Count,Reply_Count
0,2022-07-20 23:05:46+00:00,https://twitter.com/Thoby__/status/15498933553...,Thoby__,Twitter Web App,Wherever you want me to be.,I started learning Power BI through #NG30DaysO...,0,0,0,0
1,2022-07-20 22:01:56+00:00,https://twitter.com/AbdgafarYusuf/status/15498...,AbdgafarYusuf,Twitter for Android,,My submission for the #NG30DaysOfLearning Caps...,1,0,0,0
2,2022-07-20 21:55:12+00:00,https://twitter.com/Olaoluwa__Mercy/status/154...,Olaoluwa__Mercy,Twitter for Android,Ile-Ife,#30daysoflearning\nCapstone Project: Airline d...,3,1,0,1
3,2022-07-20 21:30:34+00:00,https://twitter.com/Adebayo17108247/status/154...,Adebayo17108247,Twitter for Android,Lagos,#30daysoflearning #100DaysOfCode \nI won't be ...,3,1,0,1
4,2022-07-20 21:17:53+00:00,https://twitter.com/Olaoluwa__Mercy/status/154...,Olaoluwa__Mercy,Twitter for Android,Ile-Ife,#30daysoflearning\n30 days don reach oooðŸ˜©ðŸ˜©ðŸ˜©\nC...,2,0,0,0

In [5]:
df.describe()

       Likes_Count  Retweet_Count  Quote_Count  Reply_Count
count  1242.000000    1242.000000  1242.000000  1242.000000
mean     15.004831       3.367955     0.153784     1.156200
std      42.111302       9.620387     0.613852     2.753022
min       0.000000       0.000000     0.000000     0.000000
25%       1.000000       0.000000     0.000000     0.000000
50%       2.000000       0.000000     0.000000     0.000000
75%       8.000000       2.000000     0.000000     1.000000
max     609.000000     188.000000     8.000000    30.000000